controller_list:
  - name: "eu"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
      - j7
initial:  # Define initial robot poses.
  - group: arm_group


